name: Автопостинг в Telegram

on:
  schedule:
    - cron: '0 6 * * *'   # 10:00 по Москве (UTC+3)
    - cron: '0 15 * * *'  # 19:00 по Москве (UTC+3)
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run post script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python post.py
